### ISSUE TITLE
Add search over path names

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#115]
@brettChapman [asks](https://github.com/vgteam/sequenceTubeMap/issues/97#issuecomment-792490441):
> are there any plans to add a search feature? For example if I had an entire chromosome loaded in where multiple gene paths were embedded in the graph, meaning there could be thousands of path names to select from. A search bar perhaps to go automatically to a coordinate in the selected path or to show the graph along a path matching the search terms. Such a feature would be very useful for the work I'm doing. Thanks.

While the browser's functionality to select things from dropdowns by typing while they are focused might work here, it doesn't help if the user is looking for a partial match in the middle. We ought to dig up some kind of fancy React combo box we could use here.

We also could consider what to do if the number of paths is extremely large, and not feasible to load all at once.

**Comment by brettChapman** [comment]
Hi @adamnovak, could such a search feature also be added to the xg file drop-down menu? I'm now slicing up my pangenome graph into ~60K graphs around each gene, and providing the graph as a mounted file. I'm doing this because, as mentioned in issue https://github.com/vgteam/sequenceTubeMap/issues/124 my pangenome graph (per chromosome) is too large for sequenceTubeMap to query fast enough. Thanks.

**Comment by adamnovak** [comment]
We probably could use the same control with search for all the dropdowns.
