### ISSUE TITLE
"cactus" example visualization looks wrong on the demo

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#133]
I recently updated the tube map demo, and now the "cactus" visualization example looks terrible.

I toggled the dropdown over to "cactus", hit go, and then unchecked the "Remove redundant nodes" box to see if that helped (which it didn't), and got this:

![image](https://user-images.githubusercontent.com/5062495/127878099-01ce5607-f17a-4269-96eb-911170d93530.png)

It looks like we have reads wandering from the middles of nodes to the middles of nodes, which shouldn't happen. Perhaps our example files got mixed up the last time we upgraded their formats?

**Comment by w-gao** [comment]
It looks like this happens when we're trying to make a reversed track the reference. For example, for the `backward.vg.xg` graph, I unchecked "Remove redundant nodes" and double clicked on the `rev` track, and got this: 

![image](https://user-images.githubusercontent.com/20177171/131915275-5255b028-17ce-4689-b3ae-1a2cf9080cdd.png)

The cactus example looks like a more extreme version of this. All nodes in the default `GI262359905` track are in reverse, but the other two tracks are not, so making those two the reference would produce a normal looking graph.

We probably should prevent tube maps from wrapping around reversed nodes like that, and just draw them to the left? I think we just have to update the [`straightenTrack()`](https://github.com/vgteam/sequenceTubeMap/blob/90c6d638b1b61f32e651607b087367cd2872da60/src/util/tubemap.js#L201) function to consider this case, now that [`isCompletelyReverse`](https://github.com/vgteam/sequenceTubeMap/commit/82b949fef5b229c3a57306d0ac4d18a494688429#diff-d02755cbc095a81f0817f9694c6e0a59dc3794a3b7a34cf5c3fd7cb4eda283c3L3432) was removed.

**Comment by adamnovak** [comment]
I suppose we could bring back isCompletelyReverse.

I'm not sure `straightenTrack()` changes will really help much. We could not flip the nodes around for the default track in the Cactus example, but then that track would be going backward through everything and looking wonky instead of the other two, and some of the reads might still be weird, right?

Also, the Cactus example has reads appearing to leave nodes in the middle, which I don't think should ever happen.

**Comment by w-gao** [comment]
@adamnovak Yeah, that doesn't seem to help much.. I think I'm not entirely sure how we're supposed to render reads (and the other tracks) when the first track is in reverse. Right now it is doing a lot of this (with just one read): 

![image](https://user-images.githubusercontent.com/20177171/132075507-635b0d65-8de8-49f2-82bd-2f98f5a3f7dc.png)

We're getting errors in the console too when there are more reads:
![image](https://user-images.githubusercontent.com/20177171/132074387-5002c7ee-f895-453e-976b-b6d98756eb8e.png)
