### ISSUE TITLE
Can .gfa file be visualised by sequenceTubeMap?

### ISSUE THREAD

**Issue by zmz1988** [vgteam/sequenceTubeMap#138]
Hi, thanks for this cool tool!
I just have a question about whether we could visualise the .gfa file. I know this tools is designed specifically for vg, and sorry for asking this question. But I didn't find how I can use vg to generate a pangenome graph with only assemblies sequences. I have multiple assemblies in hand, and I would prefer not to generate the .vcf files (one of the input files for vg to construct graphs) by aligning raw reads against one of the assemblies (as the reference). Could you help me out please?

Thanks in advance!

**Comment by adamnovak** [comment]
vg knows how to read GFA files. When you make the .xg file for the tube map, you should be able to pass vg the .gfa file instead of a .vg file. I think you can just use the prepare_vg.sh tube map script and pass the .gfa instead of a .vg. 

vg has `vg msga` to build a graph from sequences, but it's much worse than either PGGB or minigraph/Cactus, so we usually take in sequence-based pangenomes from other tools when there's no VCF.

Now, vg has some requirements on the GFA files it accepts; they have to only have blunt adjacencies (0 overlaps), which you can ensure with [GetBlunted](https://github.com/vgteam/GetBlunted). They also can't have a node 0, and I think all the node names have to be integers.

You also might want to limit the maximum node size with `vg chop -X 32 in.gfa >out.vg`, because GFAs often have nodes of many kilobases, and the tube map can only display entire nodes and can't cut them itself.

**Comment by zmz1988** [comment]
Great! Thanks a lot!

**Comment by adamnovak** [comment]
I'm going to close this; I think it was answered.
