### ISSUE TITLE
Disabling a haplotype path causes graph to disappear

### ISSUE THREAD

**Issue by eldariont** [vgteam/sequenceTubeMap#67]
Hi Wolfgang,

I observed a potential bug when displaying a cactus graph with 12 yeast strains (i.e. paths embedded in the xg). I would like to focus on just two of the strains which is why I disable all the others in the "Legend" panel. For most strains, that works fine. For two of the strains, however, the entire graph disappears when I disable them and it only reappears when I re-enable them.

There seem to be two different problems as I get different errors on the console for each of the strains:

Disabling strain 1:
```
Uncaught TypeError: Cannot read property '2' of undefined
    at Ie (tubemap.js:1832)
    at tubemap.js:1793
    at Array.forEach (<anonymous>)
    at tubemap.js:1576
    at de (tubemap.js:342)
    at tubemap.js:213
    at HTMLInputElement.<anonymous> (tubemap.js:3227)
Ie @ tubemap.js:1832
(anonymous) @ tubemap.js:1793
(anonymous) @ tubemap.js:1576
de @ tubemap.js:342
(anonymous) @ tubemap.js:213
(anonymous) @ tubemap.js:3227
```

Disabling strain 2:
```
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at de (tubemap.js:306)
    at tubemap.js:213
    at HTMLInputElement.<anonymous> (tubemap.js:3227)
de @ tubemap.js:306
(anonymous) @ tubemap.js:213
(anonymous) @ tubemap.js:3227
```

Unfortunately, I cannot send you the files easily as they are quite large. In case you have access to courtyard, you can find them in the following directory: `/public/groups/cgl/users/daheller/yeast_graph/sequenceTubemapData`

The problem occurs when I choose
xg: component0.vg.xg
gam: SRR4074358.cactus.subsample30.mapped.sorted.gam
path: S288C.chrII
start: 197730

Cheers,
David

**Comment by wolfib** [comment]
That's interesting. I have encountered the second type of error before when disabling haplotypes in the legend. But I previously thought that this only happens when you disable the "anchor" thread (which is the one selected in the "path name" dropdown when using custom data). This behaviour kind of made sense, since the whole graph arrangement is based on this thread.
I'll look into it and see what I can find.

**Comment by eldariont** [comment]
Yes, that would make sense but the errors happened to me when I disabled other paths.
To keep users from disabling the anchor thread you could maybe grey out the anchor thread checkbox in the legend.

**Comment by wolfib** [comment]
fixed in 2fe6c0474dd33b18753346e7adbd77509af348e1

The more common error was caused by hiding the track on which the location ruler is based on. I have changed the behavior so that now the ruler is not being displayed anymore in that case. It would be nicer to have the ruler be based on a different haplotype in those cases, but there is no guarantee that we have the exact starting position for any other haplotype in the bed file generated by vg.

Another error was caused when hiding tracks caused the remaining tracks to not have any common nodes anymore. I changed this to draw both graphs next to each other now, but I'm not sure that this always generates a proper visualization.

I used your data, which is a really nasty graph to visualize because of a lot of inverted nodes. I encountered another bug when drawing reads in the context of these inverted nodes. Again I'm not sure that the fix generates the desired behavior in all cases.

Let me know if you still encounter something fishy.

**Comment by eldariont** [comment]
Thanks Wolfgang, that has indeed fixed the errors that I was observing. You are right that the graph I need to view is not simple at all ;-)
On that node, I think I found another problem when displaying path: S288C.chrIII, start: 48355 of that very same graph. For me, the page goes completely blank after loading and an error is displayed:

```
TypeError: "t[e] is undefined"
	rt http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:43181
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:4592
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:4427
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:3178
	<anonymous> http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:61945
	value http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:62057
	jo http://localhost:3000/static/js/2.175c91fb.chunk.js:1:379443
	Po http://localhost:3000/static/js/2.175c91fb.chunk.js:1:374810
	Mo http://localhost:3000/static/js/2.175c91fb.chunk.js:1:374311
	No http://localhost:3000/static/js/2.175c91fb.chunk.js:1:373390
	Ga http://localhost:3000/static/js/2.175c91fb.chunk.js:1:372305
	enqueueSetState http://localhost:3000/static/js/2.175c91fb.chunk.js:1:337769
	setState http://localhost:3000/static/js/2.175c91fb.chunk.js:1:286126
	e http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:63080
	w http://localhost:3000/static/js/2.175c91fb.chunk.js:1:398033
	_invoke http://localhost:3000/static/js/2.175c91fb.chunk.js:1:397823
	t http://localhost:3000/static/js/2.175c91fb.chunk.js:1:398209
	r http://localhost:3000/static/js/2.175c91fb.chunk.js:1:230772
	s http://localhost:3000/static/js/2.175c91fb.chunk.js:1:230974
```

**Comment by eldariont** [comment]
I guess I should move this last problem to a new issue because it seems unrelated to the haplotypes: https://github.com/vgteam/sequenceTubeMap/issues/68

Closing this issue now.
