### ISSUE TITLE
Crazy graph layout causes crash when GAM is given

### ISSUE THREAD

**Issue by eldariont** [vgteam/sequenceTubeMap#68]
Hi Wolfgang,

because it is a separate problem, I create this issue for what I already mentioned in https://github.com/vgteam/sequenceTubeMap/issues/67#issuecomment-437467032.

The problem occurs for very complex regions in my cactus MSA graph. For example:
xg: component0.vg.xg
gam: SRR4074358.cactus.subsample30.mapped.sorted.gam
path: S288C.chrIII
start: 48355

This is how the region looks like without loading the GAM:
![grafik](https://user-images.githubusercontent.com/6477692/48589175-4ce98400-e8ef-11e8-8f8e-4ea9a3b5dc57.png)

When loading the GAM, the page goes completely blank and an error is displayed:
```
TypeError: "t[e] is undefined"
	rt http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:43181
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:4592
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:4427
	de http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:3178
	<anonymous> http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:61945
	value http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:62057
	jo http://localhost:3000/static/js/2.175c91fb.chunk.js:1:379443
	Po http://localhost:3000/static/js/2.175c91fb.chunk.js:1:374810
	Mo http://localhost:3000/static/js/2.175c91fb.chunk.js:1:374311
	No http://localhost:3000/static/js/2.175c91fb.chunk.js:1:373390
	Ga http://localhost:3000/static/js/2.175c91fb.chunk.js:1:372305
	enqueueSetState http://localhost:3000/static/js/2.175c91fb.chunk.js:1:337769
	setState http://localhost:3000/static/js/2.175c91fb.chunk.js:1:286126
	e http://localhost:3000/static/js/main.7c4f54e9.chunk.js:1:63080
	w http://localhost:3000/static/js/2.175c91fb.chunk.js:1:398033
	_invoke http://localhost:3000/static/js/2.175c91fb.chunk.js:1:397823
	t http://localhost:3000/static/js/2.175c91fb.chunk.js:1:398209
	r http://localhost:3000/static/js/2.175c91fb.chunk.js:1:230772
	s http://localhost:3000/static/js/2.175c91fb.chunk.js:1:230974
```

I suspect that in such a crazy region, the rendering of the alignments understandably fails causing the entire page to crash. I think it's totally okay that sequencetubemap is not able to render the region but maybe you find a way to make it fail more gracefully by maybe printing a message and asking the user to try again with other coordinates.

Cheers,
David

Data directory to reproduce example: `/public/groups/cgl/users/daheller/yeast_graph/sequenceTubemapData`

**Comment by wolfib** [comment]
The errors are caused by reads which pass through some nodes in the forward direction and through other nodes in the reverse direction. Commit 30fd99e0c95f49847d095685e9cdd6f72c6c8154 should fix this.

Unfortunately the rendered graph is not very useful to look at because there is just way too much going on. It seems that some of the layout algorithms reach their limits with this graph. For example, there are regions where reads are overlapping with other components, which should not really be the case. But unless something is throwing off the algorithm completely, I believe that even solving those issues would still result in a huge and confusing layout.

Did you do anything special to generate such a wild graph, or are such inputs to be expected?

**Comment by eldariont** [comment]
Thanks Wolfgang, that indeed fixed the crash.

No worries, I didn't expect this region to be very useful to look at because the layout is so wild. I'm actually quite impressed that sequencetubemap renders it alright. The graph is the result of a multiple sequence alignment of 12 assemblies so it is expected to be more complicated than a simple linear reference genome. But it is kinda strange that there are so many 1-nucleotide nodes. We will look into this.

**Comment by adamnovak** [comment]
@eldariont Did you topologically sort and renumber the nodes in this graph? Or did you just use it as it came out of the Cactus importer? 

Almost your entire GAM file is in one bin, because the reads touch nodes with dramatically different IDs, and this is dramatically slowing down access to it. That doesn't really cause tube map display issues, but it does make it take a long time to render, because it basically has to read the whole GAM.

**Comment by eldariont** [comment]
No, I didn't and just used the graph as it came out of hal2vg. But I'll add `vg ids --sort` to my pipeline. Thanks!
